"""packages

Revision ID: 8497762829f5
Revises: ed26d844362b
Create Date: 2026-02-25 19:26:21.061371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8497762829f5'
down_revision = 'ed26d844362b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('price_per_night', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('rooms_included', sa.JSON(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('breakfast_included', sa.Boolean(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_slug'))

    op.drop_table('packages')
    # ### end Alembic commands ###
